/**
 * Images de plantes importées statiquement pour React Native
 */
import { Platform } from 'react-native';

// Import des images les plus courantes avec require() pour React Native
export const PLANT_IMAGES: { [key: string]: any } = {
  'achillee-millefeuille': require('../assets/images/achillee-millefeuille.jpg'),
  'agaricus-blazei': require('../assets/images/agaricus-blazei.jpg'),
  'aigremoine': require('../assets/images/aigremoine.jpg'),
  'ail-des-ours': require('../assets/images/ail-des-ours.jpg'),
  'aloe-vera': require('../assets/images/aloe-vera.jpg'),
  'angelique': require('../assets/images/angelique.jpg'),
  'anis-vert': require('../assets/images/anis-vert.jpg'),
  'arnica': require('../assets/images/arnica.jpg'),
  'artichaut': require('../assets/images/artichaut.jpg'),
  'aubepine': require('../assets/images/aubepine.jpg'),
  'baies-dargousier': require('../assets/images/baies-dargousier.jpg'),
  'baies-de-goji': require('../assets/images/baies-de-goji.jpg'),
  'bambou-tabashir': require('../assets/images/bambou-tabashir.jpg'),
  'baobab': require('../assets/images/baobab.jpg'),
  'bardane': require('../assets/images/bardane.jpg'),
  'basilic-sacre-tulsi': require('../assets/images/basilic-sacre-tulsi.jpg'),
  'brocoli': require('../assets/images/brocoli.jpg'),
  'camomille-allemande': require('../assets/images/camomille-allemande.jpg'),
  'camomille-romaine': require('../assets/images/camomille-romaine.jpg'),
  'cannelle': require('../assets/images/cannelle.jpg'),
  'capucine': require('../assets/images/capucine.jpg'),
  'cardamome': require('../assets/images/cardamome.jpg'),
  'carotte': require('../assets/images/carotte.jpg'),
  'celeri': require('../assets/images/celeri.jpg'),
  'chicoree': require('../assets/images/chicoree.jpg'),
  'chou-kale': require('../assets/images/chou-kale.jpg'),
  'chrysanthellum-americain': require('../assets/images/chrysanthellum-americain.jpg'),
  'citronnelle': require('../assets/images/citronnelle.jpg'),
  'clou-de-girofle': require('../assets/images/clou-de-girofle.jpg'),
  'cordyceps-militaris': require('../assets/images/cordyceps-militaris.jpg'),
  'coriandre': require('../assets/images/coriandre.jpg'),
  'cresson': require('../assets/images/cresson.jpg'),
  'criniere-de-lion': require('../assets/images/criniere-de-lion.jpg'),
  'cumin': require('../assets/images/cumin.jpg'),
  'curcuma': require('../assets/images/curcuma.jpg'),
  'cynorrhodon': require('../assets/images/cynorrhodon.jpg'),
  'dulse': require('../assets/images/dulse.jpg'),
  'echinacee': require('../assets/images/echinacee.jpg'),
  'eglantier': require('../assets/images/eglantier.jpg'),
  'eleutherocoque': require('../assets/images/eleutherocoque.jpg'),
  'epices-quatre-epices': require('../assets/images/epices-quatre-epices.jpg'),
  'epinard': require('../assets/images/epinard.jpg'),
  'erable': require('../assets/images/erable.jpg'),
  'eucalyptus': require('../assets/images/eucalyptus.jpg'),
  'fenouil-doux': require('../assets/images/fenouil-doux.jpg'),
  'fenugrec': require('../assets/images/fenugrec.jpg'),
  'feuilles-de-framboisier': require('../assets/images/feuilles-de-framboisier.jpg'),
  'fumeterre': require('../assets/images/fumeterre.jpg'),
  'gentiane': require('../assets/images/gentiane.jpg'),
  'gingembre': require('../assets/images/gingembre.jpg'),
  'ginkgo-biloba': require('../assets/images/ginkgo-biloba.jpg'),
  'ginseng': require('../assets/images/ginseng.jpg'),
  'gotu-kola': require('../assets/images/gotu-kola.jpg'),
  'graines-de-chanvre': require('../assets/images/graines-de-chanvre.jpg'),
  'graines-de-citrouille': require('../assets/images/graines-de-citrouille.jpg'),
  'graines-de-sesame': require('../assets/images/graines-de-sesame.jpg'),
  'graines-de-tournesol': require('../assets/images/graines-de-tournesol.jpg'),
  'hamamelis': require('../assets/images/hamamelis.jpg'),
  'harpagophyton': require('../assets/images/harpagophyton.jpg'),
  'houblon': require('../assets/images/houblon.jpg'),
  'kombu': require('../assets/images/kombu.jpg'),
  'lavande': require('../assets/images/lavande.jpg'),
  'lavande-vraie': require('../assets/images/lavande-vraie.jpg'),
  'lierre-terrestre': require('../assets/images/lierre-terrestre.jpg'),
  'liveche': require('../assets/images/liveche.jpg'),
  'maca': require('../assets/images/maca.jpg'),
  'maitake': require('../assets/images/maitake.jpg'),
  'mauve': require('../assets/images/mauve.jpg'),
  'mauve-sylvestre': require('../assets/images/mauve-sylvestre.jpg'),
  'melisse': require('../assets/images/melisse.jpg'),
  'menthe-poivree': require('../assets/images/menthe-poivree.jpg'),
  'millepertuis': require('../assets/images/millepertuis.jpg'),
  'moringa': require('../assets/images/moringa.jpg'),
  'mousse-dirlande': require('../assets/images/mousse-dirlande.jpg'),
  'mures-sauvages': require('../assets/images/mures-sauvages.jpg'),
  'myrtilles-sauvages': require('../assets/images/myrtilles-sauvages.jpg'),
  'nigelle': require('../assets/images/nigelle.jpg'),
  'olivier': require('../assets/images/olivier.jpg'),
  'oranger': require('../assets/images/oranger.jpg'),
  'origan': require('../assets/images/origan.jpg'),
  'ortie': require('../assets/images/ortie.jpg'),
  'paille-davoine': require('../assets/images/paille-davoine.jpg'),
  'pamplemousse': require('../assets/images/pamplemousse.jpg'),
  'passiflore': require('../assets/images/passiflore.jpg'),
  'pensee-sauvage': require('../assets/images/pensee-sauvage.jpg'),
  'pin-sylvestre': require('../assets/images/pin-sylvestre.jpg'),
  'plantain-lanceole': require('../assets/images/plantain-lanceole.jpg'),
  'poivre-noir': require('../assets/images/poivre-noir.jpg'),
  'pourpier': require('../assets/images/pourpier.jpg'),
  'prele': require('../assets/images/prele.jpg'),
  'propolis': require('../assets/images/propolis.jpg'),
  'psyllium-blond': require('../assets/images/psyllium-blond.jpg'),
  'quinoa': require('../assets/images/quinoa.jpg'),
  'radis-noir': require('../assets/images/radis-noir.jpg'),
  'reglisse': require('../assets/images/reglisse.jpg'),
  'reine-des-pres': require('../assets/images/reine-des-pres.jpg'),
  'reishi': require('../assets/images/reishi.jpg'),
  'rhodiola': require('../assets/images/rhodiola.jpg'),
  'romarin': require('../assets/images/romarin.jpg'),
  'rooibos': require('../assets/images/rooibos.jpg'),
  'sauge-officinale': require('../assets/images/sauge-officinale.jpg'),
  'sauge-sclaree': require('../assets/images/sauge-sclaree.jpg'),
  'saule-blanc': require('../assets/images/saule-blanc.jpg'),
  'serpolet': require('../assets/images/serpolet.jpg'),
  'shiitake': require('../assets/images/shiitake.jpg'),
  'souci-calendula': require('../assets/images/souci-calendula.jpg'),
  'spiruline': require('../assets/images/spiruline.jpg'),
  'sureau-noir': require('../assets/images/sureau-noir.jpg'),
  'the-vert': require('../assets/images/the-vert.jpg'),
  'thym': require('../assets/images/thym.jpg'),
  'tilleul': require('../assets/images/tilleul.jpg'),
  'trefle-rouge': require('../assets/images/trefle-rouge.jpg'),
  'tussilage': require('../assets/images/tussilage.jpg'),
  'valeriane': require('../assets/images/valeriane.jpg'),
  'verge-dor': require('../assets/images/verge-dor.jpg'),
  'verveine-odorante': require('../assets/images/verveine-odorante.jpg'),
  'vigne-rouge': require('../assets/images/vigne-rouge.jpg'),
  'wakame': require('../assets/images/wakame.jpg'),
  'yerba-mate': require('../assets/images/yerba-mate.jpg'),
};

// Fonction pour obtenir l'image d'une plante (React Native compatible)
export const getPlantImageSource = (imageName: string): any => {
  return PLANT_IMAGES[imageName] || null;
};

// Pour web, utilisons une approche avec des URLs
export const getPlantImageUrl = (imageName: string): string => {
  if (Platform.OS === 'web') {
    return `/assets/images/${imageName}.jpg`;
  }
  // Pour mobile, cette fonction ne devrait pas être utilisée
  return ``;
};

// Vérifier si une image est disponible
export const isPlantImageAvailable = (imageName: string): boolean => {
  return imageName in PLANT_IMAGES;
};
