/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/body-zones`; params?: Router.UnknownInputParams; } | { pathname: `/contraindications`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/menu`; params?: Router.UnknownInputParams; } | { pathname: `/recommendations`; params?: Router.UnknownInputParams; } | { pathname: `/symptom-results`; params?: Router.UnknownInputParams; } | { pathname: `/symptom-search`; params?: Router.UnknownInputParams; } | { pathname: `/wishlist`; params?: Router.UnknownInputParams; } | { pathname: `/zone-symptoms`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/body-zones`; params?: Router.UnknownOutputParams; } | { pathname: `/contraindications`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/menu`; params?: Router.UnknownOutputParams; } | { pathname: `/recommendations`; params?: Router.UnknownOutputParams; } | { pathname: `/symptom-results`; params?: Router.UnknownOutputParams; } | { pathname: `/symptom-search`; params?: Router.UnknownOutputParams; } | { pathname: `/wishlist`; params?: Router.UnknownOutputParams; } | { pathname: `/zone-symptoms`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/body-zones${`?${string}` | `#${string}` | ''}` | `/contraindications${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/menu${`?${string}` | `#${string}` | ''}` | `/recommendations${`?${string}` | `#${string}` | ''}` | `/symptom-results${`?${string}` | `#${string}` | ''}` | `/symptom-search${`?${string}` | `#${string}` | ''}` | `/wishlist${`?${string}` | `#${string}` | ''}` | `/zone-symptoms${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/body-zones`; params?: Router.UnknownInputParams; } | { pathname: `/contraindications`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/menu`; params?: Router.UnknownInputParams; } | { pathname: `/recommendations`; params?: Router.UnknownInputParams; } | { pathname: `/symptom-results`; params?: Router.UnknownInputParams; } | { pathname: `/symptom-search`; params?: Router.UnknownInputParams; } | { pathname: `/wishlist`; params?: Router.UnknownInputParams; } | { pathname: `/zone-symptoms`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
